apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spring-boot
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
