apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: spring-boot
  labels:
    app: spring-boot-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: spring-boot-deployment
      labels:
        app: spring-boot-deployment
    spec:
      containers:
        - name: spring-boot-deployment
          image: dengyakui/spring-boot-docker:#{Build.BuildId}#
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-boot-deployment
