apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: spring-boot
  labels:
    app: spring-boot-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: spring-boot-deployment
      labels:
        app: spring-boot-deployment
    spec:
      containers:
        - name: spring-boot-deployment
          image: dengyakui/spring-boot-docker:54
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
          env:
            - name: JACOCO_OPS
              value: -javaagent:jacocoagent.jar=includes=*,output=tcpserver,address=*,port=6300,append=true
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - mountPath: "/mnt/blob"
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc-azurefile
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-boot-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker
  namespace: spring-boot
spec:
  selector:
    app: spring-boot-deployment
  ports:
    - port: 9090
  type: LoadBalancer