apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: spring-boot
spec:
  selector:
    app: spring-boot-deployment
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer